spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/backendforweb #изменить адрес на свой
    username: postgres
    password: WEyfvb56. #изменить пароль на свой
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8089